#!/bin/bash


while true; do
	
#	cp ./db-repository/rededata.* ./lib
	
#	cvs co testmud
	cd src
	make
#	make
	cd -	
	src/leu 2>> temp_log
	
	DATE=$(date +%Y-%m-%d_[%H:%M:%S])
    LOG_FILE=logLeu_${DATE}.log

    mv temp_log logs/$LOG_FILE
#	touch nohup.out 
done

exit 0
